# Generated by Django 2.2 on 2020-07-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=15)),
                ('park_time', models.DateTimeField()),
                ('unpark_time', models.DateTimeField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
