# Generated by Django 2.2 on 2020-07-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpark',
            name='unpark_time',
        ),
        migrations.AddField(
            model_name='carpark',
            name='slot',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='park_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
