# Generated by Django 2.2 on 2020-07-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_auto_20200729_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='slot',
            field=models.IntegerField(null=True),
        ),
    ]
